### ISSUE TITLE
Warning missing for Volto 15 compatibility

### ISSUE THREAD

**Issue by ionlizarazu** [eea/volto-block-style#58]
The latest version of this addon doesn't work with Volto 15 without the ImageSizeWidget.

**Comment by avoinea** [comment]
@ionlizarazu  

As there is no easy fix on this side, please do a PR to Volto core 15.x branch to include this https://github.com/plone/volto/blob/master/src/config/Widgets.jsx#L93 

Then ping Victor to make a new release for Volto 15.x

**Comment by ionlizarazu** [comment]
Fixed
